import { TimetableClass, DayOfWeek } from '../types';

export function formatWhatsAppDailySchedule(
  classes: TimetableClass[],
  day: DayOfWeek,
  batch = '25CAIBTCSB52',
  studentName = 'Student',
  semester = 'III'
): string {
  const dayClasses = classes.filter((c) => c.day === day);

  if (dayClasses.length === 0) {
    return `📚 *STUDYOS Class Schedule - ${day.toUpperCase()}*\n\nHey ${studentName}! 🎉 No classes scheduled for ${day}. Great time for self-study and coding practice!\n\n_Batch: ${batch} | Sem: ${semester}_`;
  }

  const sorted = [...dayClasses].sort((a, b) => (a?.startTime || '').localeCompare(b?.startTime || ''));

  let msg = `📚 *STUDYOS CLASS ROOMS & TIMINGS - ${day.toUpperCase()}*\n`;
  msg += `👤 Student: *${studentName}*\n`;
  msg += `🏛️ Batch: *${batch}* | Semester: *${semester}*\n`;
  msg += `📅 Day: *${day}* (${sorted.length} Sessions)\n`;
  msg += `━━━━━━━━━━━━━━━━━━━━━\n\n`;

  sorted.forEach((c, idx) => {
    const typeTag = c.type === 'Lab' ? '💻 [LAB]' : '📖 [LECTURE]';
    msg += `*${idx + 1}. ${c.startTime} - ${c.endTime}*\n`;
    msg += `   📌 *${c.subjectName}*\n`;
    msg += `   📍 Room: *${c.room || 'TBA'}* ${typeTag}\n`;
    if (c.faculty) {
      msg += `   👨‍🏫 Faculty: ${c.faculty}\n`;
    }
    msg += `\n`;
  });

  msg += `━━━━━━━━━━━━━━━━━━━━━\n`;
  msg += `💡 *StudyOS Reminder:* Be on time and log your attendance!\n`;
  msg += `🚀 Generated by *StudyOS Academic Dashboard*`;

  return msg;
}

export function formatWhatsAppFullWeekSchedule(
  classes: TimetableClass[],
  batch = '25CAIBTCSB52',
  studentName = 'Student',
  semester = 'III'
): string {
  const days: DayOfWeek[] = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'];

  let msg = `🎓 *STUDYOS COMPLETE WEEKLY ROOM & TIMETABLE MATRIX*\n`;
  msg += `👤 Student: *${studentName}*\n`;
  msg += `🏛️ Batch: *${batch}* | Semester: *${semester}*\n`;
  msg += `━━━━━━━━━━━━━━━━━━━━━\n\n`;

  days.forEach((day) => {
    const dayClasses = classes
      .filter((c) => c.day === day)
      .sort((a, b) => (a?.startTime || '').localeCompare(b?.startTime || ''));

    msg += `📅 *${day.toUpperCase()}* (${dayClasses.length} sessions)\n`;
    if (dayClasses.length === 0) {
      msg += `  — No classes scheduled\n\n`;
    } else {
      dayClasses.forEach((c) => {
        const typeTag = c.type === 'Lab' ? '[LAB]' : '[LEC]';
        msg += `  • ${c.startTime}-${c.endTime}: *${c.room || 'TBA'}* | ${c.subjectName} ${typeTag}\n`;
      });
      msg += `\n`;
    }
  });

  msg += `━━━━━━━━━━━━━━━━━━━━━\n`;
  msg += `🚀 Generated by *StudyOS Academic Dashboard*`;
  return msg;
}

export function getWhatsAppShareUrl(phone: string, text: string): string {
  let cleanPhone = phone.replace(/\D/g, '');
  if (!cleanPhone.startsWith('91') && cleanPhone.length === 10) {
    cleanPhone = '91' + cleanPhone;
  }
  const encoded = encodeURIComponent(text);
  return `https://wa.me/${cleanPhone}?text=${encoded}`;
}
